### PR TITLE
fix(docs): strings.xml -> values.xml in README

### PR DESCRIPTION
**Pull request by DismissedGuy**
`app_base_url` seems to have been moved to values.xml.

### CODE REVIEW

**Comment by binwiederhier** [comment]
Thanks!

**Comment by binwiederhier** [comment]
It may also be worth linking to https://docs.ntfy.sh/develop/#android-app since that's where the up-to-date docs are.

**Comment by DismissedGuy** [comment]
I think in that case it might be better to drop the building instructions from this repo altogether, just to avoid having possibly conflicting information in the future (if the instructions here don't get updated). I also just noticed that the FDroid instructions in the docs suggest stripping google dependencies, whereas this repo doesn't.

**Comment by binwiederhier** [comment]
I'm happily accepting PRs for this stuff, but I sadly don't have a ton of time right now to do it myself.

**Pull request merged**
